# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9c3040927bc6577753dc01be7f2d7ea01e9d3213baf8c6692da8236fdfe5695260187864a2ed09f7590cf0273d886e85d3521940a44d6eea6b48f2c40ff7c46

test:
  secret_key_base: fab371a51581f7bf29c66d6edd1487537a45d1fdf5c25d40beadae067df2f9003e917fc2de783203ea5dcde6758b33eaf6a7090fe1640fdba77c3b2ec3883275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
